[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
LinearSolveAutotune = "67398393-80e8-4254-b7e4-1b9a36a3c5b6"
LinearSolvePyAMG = "7a56c47d-7ab1-4e99-b0e3-2952e463d64a"
SciMLOperators = "c0aeaf25-5076-4817-a8d5-81caf7dfa961"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[sources]
LinearSolve = {path = "/home/runner/_work/LinearSolve.jl/LinearSolve.jl"}
LinearSolveAutotune = {path = "../lib/LinearSolveAutotune"}
LinearSolvePyAMG = {path = "../lib/LinearSolvePyAMG"}

[compat]
Documenter = "1"
LinearSolve = "4"
LinearSolveAutotune = "1.1"
LinearSolvePyAMG = "1"
SciMLOperators = "1"
